name = "futurecom-ads-dashboard"
# This is the crucial top-level property for Cloudflare Pages to identify
# where your static assets are located after your build command runs.
pages_build_output_dir = "public"

# Ensure this compatibility date is current or slightly in the future
# to use the latest Workers runtime features.
compatibility_date = "2024-06-15"

# Environment variables for your Pages Functions
# DATA_URL will be used by your /api/ads function
[vars]
DATA_URL = "https://opensheet.elk.sh/1n66ctdtHrySM957k4TFRYfO6JRmJ9Y5oBGaIMS3g8PY/result"
# JWT_SECRET is used for signing and verifying JWTs.
# **IMPORTANT**: For production, set this as a secure secret via `wrangler secret put JWT_SECRET`
# and remove it from this file to prevent it from being committed to your Git repository.
JWT_SECRET = "your_super_secret_jwt_key_CHANGE_THIS_IN_PRODUCTION_AND_USE_WRANGLER_SECRET"

# D1 database binding for your Pages Functions
# This allows your functions to interact with your D1 database using `env.DB`
[d1_databases]
DB = { binding = "DB", database_name = "aduserdb", database_id = "47348cd6-9639-4e6a-9fa3-dcddf6fd7af8" } # REPLACE THIS WITH YOUR ACTUAL D1 DATABASE ID
